spring.application.name=fstproject


spring.datasource.url=jdbc:postgresql://dpg-d8d9qbkp3tds73fbfa2g-a.oregon-postgres.render.com:5432/customer_crud_db_fk8v
spring.datasource.username=customer_crud_db_fk8v_user
spring.datasource.password=JDDtuiSZPMX48M5HxEb81vnMxZvKnk5q
spring.datasource.driver-class-name=org.postgresql.Driver



